spring:
  application:
    name: social-network-v1
  datasource:
    url: jdbc:mysql://localhost:3306/social_network_v1
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    servlet:
      load-on-startup: 1
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  privateKey: 8acnkodIBNY6iRCuppO1AUCkOKJFBzjCIZuEqgWPCFq/ags2ANcd9PAO8RoGd9fp

server:
  address: localhost
  port: 8080