spring:
  application:
    name: social-network-v1
  datasource:
    url: ${DBMS_CONNECTION:jdbc:mariadb://localhost:3306/social_network_v1}
    username: root
    password: ${MYSQL_ROOT_PASSWORD:}
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
  mvc:
    servlet:
      load-on-startup: 1
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

jwt:
  privateKey: 8acnkodIBNY6iRCuppO1AUCkOKJFBzjCIZuEqgWPCFq/ags2ANcd9PAO8RoGd9fp

server:
  address: 0.0.0.0
  port: 8080

cors:
  allowed:
    origins: https://social-network-react-js-mosxy6ru7-nhoclaholas-projects.vercel.app, http://localhost:3000, https://social-network-react-js-ui.vercel.app